### ISSUE TITLE
No description

### ISSUE THREAD

**Issue by developersarm** [mitaly/News-Aggregator#1]
There is no description about this project. I'm certainly new to android. Could you please describe in short what this project does and how do I run it on my system?

**Comment by mitaly** [comment]
This is very simple project using list view and web view in android.
Basically, I have done it when I was at initial stage while learning
android.
This is News Aggregator app. It displays newspapers of different languages
of India, in a list. By clicking on any, it opens the website of that
newspaper.
To run it on your system, you first have to install android studio (hope
that you must have installed). Then clone this project and copy the project
folder into "Android Studio Projects" directory, which is created after
installing android studio. There's another method to run the project. You
can directly import the project but firstly you need to clone the project.
If you face any problem, you can ask.

**Comment by developersarm** [comment]
You should add a readme.md file to your project. It's common in open source community.

**Comment by developersarm** [comment]
After doing it, you can close this issue.

**Comment by mitaly** [comment]
I have added readme file. You can go through that.
